"""Initial solution generation.

``solve`` sends a formatted task prompt to the model.
``extract_code`` pulls the Python implementation out of the model response.
"""

from __future__ import annotations

import re

from stagewise_coding_agent_fragility.models.base import ModelClient
from stagewise_coding_agent_fragility.models.response_types import ModelResponse

# Matches a fenced code block: ```python ... ``` or ``` ... ```
_CODE_BLOCK_RE = re.compile(r"```(?:python)?[ \t]*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def solve(
    task_prompt: str,
    model: ModelClient,
    temperature: float,
    max_tokens: int,
    timeout_seconds: float,
) -> ModelResponse:
    """Send the task prompt to the model and return the raw response.

    Args:
        task_prompt: The full prompt string, already formatted by the prompting layer.
        model: The model client to use.
        temperature: Sampling temperature.
        max_tokens: Maximum tokens to generate.
        timeout_seconds: HTTP request timeout in seconds.

    Returns:
        The raw ``ModelResponse`` from the model.
    """
    return model.complete(
        task_prompt,
        temperature=temperature,
        max_tokens=max_tokens,
        timeout_seconds=timeout_seconds,
    )


def extract_code(response_text: str) -> str:
    """Extract Python source code from a model response string.

    Searches for the first fenced code block (```python ... ``` or ``` ... ```).
    Falls back to the raw response text when no fence is found.

    Args:
        response_text: The full text generated by the model.

    Returns:
        Extracted Python source code as a plain string.
    """
    match = _CODE_BLOCK_RE.search(response_text)
    if match:
        return match.group(1).rstrip()
    return response_text.strip()

